Enhance CI/CD workflows by adding comprehensive testing steps and adjusting dependencies for unit tests

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -178,5 +178,86 @@ jobs:
                 key: 
                     cache-site-macos-${{ github.run_number }}
                 enableCrossOsArchive:
-                    true
+                    true    
+ 
+        # ------------------------------------------------------------------------------------------------------
+        # Install msbild && Build Ginger Solution
+        # ------------------------------------------------------------------------------------------------------
+        -   name: Add msbuild to PATH
+            if: ${{github.workflow == 'Ginger Windows Test'}} 
+            uses: microsoft/setup-msbuild@v1.0.2       
+
+        # ------------------------------------------------------------------------------------------------------
+        # Start Testing 
+        # ------------------------------------------------------------------------------------------------------
+        -   name: 'Testing GingerUtilsTest'
+            if: success() || failure()  
+            run: dotnet test  Ginger/GingerUtilsTest --configuration ${{ env.BUILD_CONFIGURATION }} --logger trx --results-directory D:\a\TestResults --verbosity=normal
+
+        -   name: 'Testing GingerCoreCommonTest'
+            if: success() || failure()  
+            run: dotnet test  Ginger/GingerCoreCommonTest --configuration ${{ env.BUILD_CONFIGURATION }} --logger trx --results-directory D:\a\TestResults --verbosity=normal
+
+        -   name: 'Testing GingerCoreNETUnitTest'
+            if: success() || failure()  
+            run: dotnet test  Ginger/GingerCoreNETUnitTest --configuration ${{ env.BUILD_CONFIGURATION }} --logger trx --results-directory D:\a\TestResults --verbosity=normal
+
+        -   name: 'Testing GingerPluginCoreTest'
+            if: success() || failure()  
+            run: dotnet test  Ginger/GingerPluginCoreTest --configuration ${{ env.BUILD_CONFIGURATION }} --logger trx --results-directory D:\a\TestResults --verbosity=normal
+
+        -   name: 'Testing GingerConsoleTest'
+            if: success() || failure()  
+            run: dotnet test  Ginger/GingerConsoleTest --configuration ${{ env.BUILD_CONFIGURATION }} --logger trx --results-directory D:\a\TestResults --verbosity=normal
+
+        -   name: 'Testing GingerAutoPilotTest'
+            if: success() || failure()  
+            run: dotnet test  Ginger/GingerAutoPilotTest --configuration ${{ env.BUILD_CONFIGURATION }} --logger trx --results-directory D:\a\TestResults --verbosity=normal     
+
+        # ------------------------------------------------------------------------------------------------------
+        # Run .Net Framework tests using powershell and publish the results
+        # ------------------------------------------------------------------------------------------------------
+        -   name: Run tests for Ginger .NetFramework *Test Dlls for Windows
+            if: (success() || failure()) && (runner.os == 'Windows')        # run this step even if previous step failed and if the OS is Windows
+            run: powershell -file "TestDotNetFrameworkGithub.ps1"
+
+        # ------------------------------------------------------------------------------------------------------
+        # Run Standalone CLI Test
+        # ------------------------------------------------------------------------------------------------------          
+        -   name: Run Standalone CLI Test for Linux
+            if: (success() || failure()) && (runner.os == 'Linux')       # run this step even if previous step failed
+            shell: bash
+            run: |
+                pwd 
+                ls -alt
+                chmod +x CLITestsGithub.sh
+                sudo apt install dos2unix
+                dos2unix -b CLITestsGithub.sh
+                ./CLITestsGithub.sh
+
+        # ------------------------------------------------------------------------------------------------------
+        # Publish Test Results
+        # ------------------------------------------------------------------------------------------------------
+        -   name: Test Report - Windows
+            uses: dorny/test-reporter@v1
+            if: (success() || failure()) && (runner.os == 'Windows')        # run this step even if previous step failed
+            with:
+                name: Generate Unit Test Report for Windows    # Name of the check run which will be created
+                path: "D:/a/TestResults/*.trx"                # Path to test results
+                reporter: dotnet-trx            # Format of test results
             
+        -   name: Test Report - Linux
+            uses: dorny/test-reporter@v1
+            if: (success() || failure())   && (runner.os == 'Linux')      # run this step even if previous step failed
+            with:
+                name: Generate Unit Test Report for Linux    # Name of the check run which will be created
+                path: "**/*.trx"                # Path to test results
+                reporter: dotnet-trx            # Format of test results 
+
+        -   name: Test Report - MacOS
+            uses: dorny/test-reporter@v1
+            if: (success() || failure())  && (runner.os == 'macOS')       # run this step even if previous step failed
+            with:
+                name: Generate Unit Test Report for MacOS    # Name of the check run which will be created
+                path: "**/*.trx"                # Path to test results
+                reporter: dotnet-trx            # Format of test results    
